# Homebrew Cask for Aranet GUI
# This file is automatically generated by the release workflow.
#
# Install with:
#   brew tap cameronrye/aranet
#   brew install --cask aranet-gui
#
# This installs the native macOS .app bundle to /Applications.

cask "aranet-gui" do
  arch arm: "aarch64-apple-darwin", intel: "x86_64-apple-darwin"
  sha_arm = "d80d41bd8ddeaba5ded8b618714da71702ba75a469b0af17fb28c60351d2ac21"
  sha_intel = "c520c6238ac3014d48ecc472c1b3972507661a16e50c7f37866b096f6ac798bb"

  version "0.1.13"
  sha256 arm: sha_arm, intel: sha_intel

  url "https://github.com/cameronrye/aranet/releases/download/v#{version}/Aranet-#{arch}.dmg"
  name "Aranet"
  desc "Desktop application for Aranet environmental sensors"
  homepage "https://github.com/cameronrye/aranet"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: ">= :big_sur"

  app "Aranet.app"

  zap trash: [
    "~/Library/Application Support/dev.rye.aranet",
    "~/Library/Caches/dev.rye.aranet",
    "~/Library/Preferences/dev.rye.aranet.plist",
    "~/Library/Saved Application State/dev.rye.aranet.savedState",
  ]

  caveats <<~EOS
    Aranet GUI requires Bluetooth access.

    Grant Bluetooth permission when prompted on first launch, or go to:
      System Preferences > Privacy & Security > Bluetooth

    For CLI tools, install the formula instead:
      brew install cameronrye/aranet/aranet
  EOS
end

