# Homebrew Cask for Aranet GUI
# This file is automatically generated by the release workflow.
#
# Install with:
#   brew tap cameronrye/aranet
#   brew install --cask aranet-gui
#
# This installs the native macOS .app bundle to /Applications.

cask "aranet-gui" do
  arch arm: "aarch64-apple-darwin", intel: "x86_64-apple-darwin"
  sha_arm = "39565b13b3e36c1691bfe5a2154de9ab586fc4b4d4128de00dbd48a6541af28a"
  sha_intel = "8510f64fcde54b8010358dbbb5f02f48ede7a624124a18cc0fe0e78314a65733"

  version "0.1.9"
  sha256 arm: sha_arm, intel: sha_intel

  url "https://github.com/cameronrye/aranet/releases/download/v#{version}/Aranet-#{arch}.dmg"
  name "Aranet"
  desc "Desktop application for Aranet environmental sensors"
  homepage "https://github.com/cameronrye/aranet"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: ">= :big_sur"

  app "Aranet.app"

  zap trash: [
    "~/Library/Application Support/dev.rye.aranet",
    "~/Library/Caches/dev.rye.aranet",
    "~/Library/Preferences/dev.rye.aranet.plist",
    "~/Library/Saved Application State/dev.rye.aranet.savedState",
  ]

  caveats <<~EOS
    Aranet GUI requires Bluetooth access.

    Grant Bluetooth permission when prompted on first launch, or go to:
      System Preferences > Privacy & Security > Bluetooth

    For CLI tools, install the formula instead:
      brew install cameronrye/aranet/aranet
  EOS
end

