# Homebrew Cask for Aranet GUI
# This file is automatically generated by the release workflow.
#
# Install with:
#   brew tap cameronrye/aranet
#   brew install --cask aranet-gui
#
# This installs the native macOS .app bundle to /Applications.

cask "aranet-gui" do
  arch arm: "aarch64-apple-darwin", intel: "x86_64-apple-darwin"
  sha_arm = "8704f6b1f53ffea9dd27df628789bd81137d90ebfd78db17c23dfa0c5b0d01b9"
  sha_intel = "237f5739d127f4ffbf5c576b5853c05eabf274f100ba8da730936e4029eec409"

  version "0.1.12"
  sha256 arm: sha_arm, intel: sha_intel

  url "https://github.com/cameronrye/aranet/releases/download/v#{version}/Aranet-#{arch}.dmg"
  name "Aranet"
  desc "Desktop application for Aranet environmental sensors"
  homepage "https://github.com/cameronrye/aranet"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: ">= :big_sur"

  app "Aranet.app"

  zap trash: [
    "~/Library/Application Support/dev.rye.aranet",
    "~/Library/Caches/dev.rye.aranet",
    "~/Library/Preferences/dev.rye.aranet.plist",
    "~/Library/Saved Application State/dev.rye.aranet.savedState",
  ]

  caveats <<~EOS
    Aranet GUI requires Bluetooth access.

    Grant Bluetooth permission when prompted on first launch, or go to:
      System Preferences > Privacy & Security > Bluetooth

    For CLI tools, install the formula instead:
      brew install cameronrye/aranet/aranet
  EOS
end

