# Homebrew formula for Aranet CLI and GUI
# This file is automatically generated by the release workflow.
#
# Install with:
#   brew tap cameronrye/aranet
#   brew install aranet
#
# This installs both the CLI (aranet) and GUI (aranet-gui) binaries.
# For the native macOS app bundle, use: brew install --cask aranet-gui

class Aranet < Formula
  desc "CLI and GUI for Aranet environmental sensors (CO2, radon, temperature, humidity)"
  homepage "https://github.com/cameronrye/aranet"
  version "0.1.11"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/cameronrye/aranet/releases/download/v0.1.11/aranet-cli-aarch64-apple-darwin.tar.xz"
      sha256 "2bf55026dc6f88e6cc93bebc188421eb90b8c68694926e683828351ec9775fec"

      resource "gui" do
        url "https://github.com/cameronrye/aranet/releases/download/v0.1.11/aranet-gui-aarch64-apple-darwin.tar.xz"
        sha256 "8f7f421b2a61312dea74eee573e32ea5072c06b42a78ab2f1bebc59e3cdaa19b"
      end
    end
    on_intel do
      url "https://github.com/cameronrye/aranet/releases/download/v0.1.11/aranet-cli-x86_64-apple-darwin.tar.xz"
      sha256 "0bc12126824dc303bcc0358f2eac7b5e3eb284c1745c64602b64fd71550290ad"

      resource "gui" do
        url "https://github.com/cameronrye/aranet/releases/download/v0.1.11/aranet-gui-x86_64-apple-darwin.tar.xz"
        sha256 "095f1b45f369fe15c8e1e61ba64baa432e7f314ccaa308e35eba73fd24a431a7"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cameronrye/aranet/releases/download/v0.1.11/aranet-cli-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "03bb0dad0a849e9df957d2221d770b24b308687f30f82a5b3fe2c4881827d708"

      resource "gui" do
        url "https://github.com/cameronrye/aranet/releases/download/v0.1.11/aranet-gui-x86_64-unknown-linux-gnu.tar.xz"
        sha256 "973b4163e8e821c08767afacf34a2fb44363aa3dcf682ea8375478c160f9bcce"
      end
    end
  end

  def install
    bin.install "aranet"

    # Install GUI binary from resource
    resource("gui").stage do
      bin.install "aranet-gui"
    end
  end

  def caveats
    <<~EOS
      Aranet requires Bluetooth access.

      On macOS:
        Grant Bluetooth permission when prompted, or add Terminal/iTerm
        to System Preferences > Privacy & Security > Bluetooth.

      Binaries installed:
        aranet      - Command-line interface
        aranet-gui  - Native desktop GUI

      For the macOS .app bundle with Dock icon, install the cask:
        brew install --cask cameronrye/aranet/aranet-gui

      Quick start:
        aranet scan              # Find nearby devices
        aranet read              # Read current values
        aranet-gui               # Launch the GUI
    EOS
  end

  test do
    assert_match "CLI for Aranet environmental sensors", shell_output("#{bin}/aranet --help")
    assert_match version.to_s, shell_output("#{bin}/aranet --version")
  end
end

