# Homebrew formula for Aranet CLI and GUI
# This file is automatically generated by the release workflow.
#
# Install with:
#   brew tap cameronrye/aranet
#   brew install aranet
#
# This installs both the CLI (aranet) and GUI (aranet-gui) binaries.
# For the native macOS app bundle, use: brew install --cask aranet-gui

class Aranet < Formula
  desc "CLI and GUI for Aranet environmental sensors (CO2, radon, temperature, humidity)"
  homepage "https://github.com/cameronrye/aranet"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/cameronrye/aranet/releases/download/v0.2.0/aranet-cli-aarch64-apple-darwin.tar.xz"
      sha256 "0d4afd3f12427ff77485a936635026cbaa65ade50d6250aa224a5c7fea60dab4"

      resource "gui" do
        url "https://github.com/cameronrye/aranet/releases/download/v0.2.0/aranet-gui-aarch64-apple-darwin.tar.xz"
        sha256 "a0c93ab99a484cc8a7596d51d1fa71c030f33ed84d4f8b0a7c0b57e735738654"
      end
    end
    on_intel do
      url "https://github.com/cameronrye/aranet/releases/download/v0.2.0/aranet-cli-x86_64-apple-darwin.tar.xz"
      sha256 "2a947c5ca6eff1542eaff558177236f134f327533be3d67d1e3eff0d4a382dcd"

      resource "gui" do
        url "https://github.com/cameronrye/aranet/releases/download/v0.2.0/aranet-gui-x86_64-apple-darwin.tar.xz"
        sha256 "42807bcffe982fc94d99a81d4954715e0370c422e2c057cc9bbcd0475f9e3b27"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cameronrye/aranet/releases/download/v0.2.0/aranet-cli-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "1b62756881e68bed8487b320de3db643f5b90ecdd54407436c3535ddb501beb0"

      resource "gui" do
        url "https://github.com/cameronrye/aranet/releases/download/v0.2.0/aranet-gui-x86_64-unknown-linux-gnu.tar.xz"
        sha256 "4699d25d353b30681f0c377f2ff0c34a0f594f5a67cc37d792e81ae3b2efd87a"
      end
    end
  end

  def install
    bin.install "aranet"

    # Install GUI binary from resource
    resource("gui").stage do
      bin.install "aranet-gui"
    end
  end

  def caveats
    <<~EOS
      Aranet requires Bluetooth access.

      On macOS:
        Grant Bluetooth permission when prompted, or add Terminal/iTerm
        to System Preferences > Privacy & Security > Bluetooth.

      Binaries installed:
        aranet      - Command-line interface
        aranet-gui  - Native desktop GUI

      For the macOS .app bundle with Dock icon, install the cask:
        brew install --cask cameronrye/aranet/aranet-gui

      Quick start:
        aranet scan              # Find nearby devices
        aranet read              # Read current values
        aranet-gui               # Launch the GUI
    EOS
  end

  test do
    assert_match "CLI for Aranet environmental sensors", shell_output("#{bin}/aranet --help")
    assert_match version.to_s, shell_output("#{bin}/aranet --version")
  end
end

