# Homebrew formula for Aranet CLI and GUI
# This file is automatically generated by the release workflow.
#
# Install with:
#   brew tap cameronrye/aranet
#   brew install aranet
#
# This installs both the CLI (aranet) and GUI (aranet-gui) binaries.
# For the native macOS app bundle, use: brew install --cask aranet-gui

class Aranet < Formula
  desc "CLI and GUI for Aranet environmental sensors (CO2, radon, temperature, humidity)"
  homepage "https://github.com/cameronrye/aranet"
  version "0.1.13"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/cameronrye/aranet/releases/download/v0.1.13/aranet-cli-aarch64-apple-darwin.tar.xz"
      sha256 "f22865efa28b672ea16722d7ee399488eab5b314cb368c9c1f3b043294edc16e"

      resource "gui" do
        url "https://github.com/cameronrye/aranet/releases/download/v0.1.13/aranet-gui-aarch64-apple-darwin.tar.xz"
        sha256 "e61b38d1b0cc635d5383073ad1f5a4dff28a60d2bb4ce5bc7b84d2b330df824a"
      end
    end
    on_intel do
      url "https://github.com/cameronrye/aranet/releases/download/v0.1.13/aranet-cli-x86_64-apple-darwin.tar.xz"
      sha256 "3184fec574c043d9c5f5d9419b42bcf5e98db70dc854464bf78743b76dfc8961"

      resource "gui" do
        url "https://github.com/cameronrye/aranet/releases/download/v0.1.13/aranet-gui-x86_64-apple-darwin.tar.xz"
        sha256 "a8a9050d125f6723930b2cafcc849d41af1b8773baad6182bc709f3d37a608ae"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cameronrye/aranet/releases/download/v0.1.13/aranet-cli-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "cc5c5da5c4c2cae9991a06c55de3102c4604a36787550671935bfdc756d7390c"

      resource "gui" do
        url "https://github.com/cameronrye/aranet/releases/download/v0.1.13/aranet-gui-x86_64-unknown-linux-gnu.tar.xz"
        sha256 "b86283f5ea35f53e4f8db630d4c259d593f3a79ff91e26e77bda8b1df93510a8"
      end
    end
  end

  def install
    bin.install "aranet"

    # Install GUI binary from resource
    resource("gui").stage do
      bin.install "aranet-gui"
    end
  end

  def caveats
    <<~EOS
      Aranet requires Bluetooth access.

      On macOS:
        Grant Bluetooth permission when prompted, or add Terminal/iTerm
        to System Preferences > Privacy & Security > Bluetooth.

      Binaries installed:
        aranet      - Command-line interface
        aranet-gui  - Native desktop GUI

      For the macOS .app bundle with Dock icon, install the cask:
        brew install --cask cameronrye/aranet/aranet-gui

      Quick start:
        aranet scan              # Find nearby devices
        aranet read              # Read current values
        aranet-gui               # Launch the GUI
    EOS
  end

  test do
    assert_match "CLI for Aranet environmental sensors", shell_output("#{bin}/aranet --help")
    assert_match version.to_s, shell_output("#{bin}/aranet --version")
  end
end

